# Spring properties

spring:
  application:
    name: consumer-service
    
    
# Eureka properties

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
# 

server:
  error:
    whitelabel:
      enabled: false      
  port: 8082
